### ISSUE TITLE
PyPI Release for this Repository?

### ISSUE THREAD

**Issue by TrevisGordan** [matrix-nio/vodozemac-python#9]
Hi Team,

Quick question: Will there be a PyPI release for this repository?

I’ve been following the developments here for quite some time and am excited about the progress. I noticed that @PaarthShah  and @poljar already host a vodozemac package on PyPI (published in late 2021):
https://pypi.org/project/vodozemac/

Will this package be updated with the latest changes? I’m particularly looking forward to using your Python bindings for vodozemac as a replacement for olm, especially now that PkEncryption has been implemented.

Thanks in advance for the info - and the work you put in!

Cheers!

**Comment by PaarthShah** [comment]
I'd be willing to publish a release with imperfect docs if there's a desire for it (which it now sounds like there is).

**Comment by poljar** [comment]
Sounds good to me, @PaarthShah to confirm, you'll be doing the releasing?

**Comment by TrevisGordan** [comment]
Thank you, big time @PaarthShah and all!
